--
-- PostgreSQL database dump
--

-- Dumped from database version 16.8
-- Dumped by pg_dump version 16.8

-- Started on 2025-03-16 20:31:58

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 6 (class 2615 OID 16450)
-- Name: wohnungshelden; Type: SCHEMA; Schema: -; Owner: test
--

CREATE SCHEMA wohnungshelden;


ALTER SCHEMA wohnungshelden OWNER TO test;

--
-- TOC entry 842 (class 1247 OID 16536)
-- Name: Salutation_enum; Type: TYPE; Schema: wohnungshelden; Owner: test
--

CREATE TYPE wohnungshelden."Salutation_enum" AS ENUM (
    'MR',
    'MRS'
);


ALTER TYPE wohnungshelden."Salutation_enum" OWNER TO test;

--
-- TOC entry 845 (class 1247 OID 16542)
-- Name: Source_enum; Type: TYPE; Schema: wohnungshelden; Owner: test
--

CREATE TYPE wohnungshelden."Source_enum" AS ENUM (
    'MANUAL',
    'PORTAL'
);


ALTER TYPE wohnungshelden."Source_enum" OWNER TO test;

--
-- TOC entry 848 (class 1247 OID 16548)
-- Name: Status_enum; Type: TYPE; Schema: wohnungshelden; Owner: test
--

CREATE TYPE wohnungshelden."Status_enum" AS ENUM (
    'CREATED',
    'INVITED',
    'DECLINED'
);


ALTER TYPE wohnungshelden."Status_enum" OWNER TO test;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 216 (class 1259 OID 16556)
-- Name: applicants; Type: TABLE; Schema: wohnungshelden; Owner: test
--

CREATE TABLE wohnungshelden.applicants (
    id bigint NOT NULL,
    email character varying(200) NOT NULL,
    salutation wohnungshelden."Salutation_enum",
    first_name character varying(200),
    last_name character varying(200) NOT NULL,
    number_of_persons integer,
    wbs_present boolean,
    earliest_move_in_date date,
    pets boolean,
    status wohnungshelden."Status_enum",
    applicant_comment character varying(1000),
    user_comment character varying(1000),
    creation_timestamp timestamp with time zone,
    property_id bigint,
    creation_source wohnungshelden."Source_enum",
    CONSTRAINT validate_email CHECK (((email)::text ~* '^[A-Za-z0-9._+%-]+@[A-Za-z0-9.-]+[.][A-Za-z]+$'::text))
);


ALTER TABLE wohnungshelden.applicants OWNER TO test;

--
-- TOC entry 217 (class 1259 OID 16568)
-- Name: applicants_seq; Type: SEQUENCE; Schema: wohnungshelden; Owner: test
--

CREATE SEQUENCE wohnungshelden.applicants_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE wohnungshelden.applicants_seq OWNER TO test;

--
-- TOC entry 4797 (class 0 OID 0)
-- Dependencies: 217
-- Name: applicants_seq; Type: SEQUENCE OWNED BY; Schema: wohnungshelden; Owner: test
--

ALTER SEQUENCE wohnungshelden.applicants_seq OWNED BY wohnungshelden.applicants.id;


--
-- TOC entry 4790 (class 0 OID 16556)
-- Dependencies: 216
-- Data for Name: applicants; Type: TABLE DATA; Schema: wohnungshelden; Owner: test
--

INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (1, 'iatmore0@msu.edu', 'MR', 'Bécassine', 'Atmore', 1, true, '2024-09-28', false, 'DECLINED', 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.', '2024-07-23 08:23:07+02', 41, 'MANUAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (2, 'kluckham1@usnews.com', 'MRS', NULL, 'Luckham', 3, true, '2024-12-18', true, 'INVITED', 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.', 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl.', '2024-11-12 23:26:13+01', 5, 'MANUAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (3, 'csisnett2@nyu.edu', 'MR', 'Mélia', 'Sisnett', 6, false, '2024-03-22', false, 'CREATED', 'Aenean sit amet justo.', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', '2024-07-22 15:58:19+02', 38, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (4, 'jniesel3@angelfire.com', 'MRS', 'Mélia', 'Niesel', 4, false, '2024-05-17', true, 'CREATED', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.', 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', '2025-01-30 06:16:02+01', 41, 'MANUAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (5, 'opashby4@cmu.edu', 'MR', NULL, 'Pashby', 9, true, '2025-03-09', NULL, 'DECLINED', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.', 'Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.', '2025-01-26 02:19:32+01', 29, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (6, 'ashoveller5@usda.gov', 'MRS', 'Amélie', 'Shoveller', 7, true, '2024-12-29', true, 'CREATED', 'Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', '2024-12-30 04:29:41+01', 31, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (7, 'lawcoate6@yandex.ru', 'MR', 'Kù', 'Awcoate', 6, true, '2025-01-10', NULL, 'INVITED', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis.', 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', '2024-06-03 13:51:43+02', 28, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (8, 'cbertram7@cam.ac.uk', 'MR', 'Kuí', 'Bertram', 1, true, '2024-04-16', true, 'DECLINED', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', '2025-01-28 19:05:21+01', 37, 'MANUAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (9, 'bbeldom8@senate.gov', 'MRS', 'Görel', 'Beldom', 1, true, '2025-01-06', NULL, 'INVITED', 'Praesent blandit.', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', '2024-07-22 16:59:39+02', 40, 'MANUAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (10, 'cjosovich9@mac.com', 'MR', 'Cloé', 'Josovich', 6, false, '2024-07-27', NULL, 'INVITED', 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.', 'Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc.', '2024-12-06 06:01:09+01', 43, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (11, 'ckarmela@pinterest.com', 'MR', 'Lyséa', 'Karmel', 10, false, '2024-05-07', NULL, 'INVITED', 'Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus.', '2024-05-03 15:35:04+02', 19, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (12, 'tbarthrupb@flavors.me', 'MRS', 'Kuí', 'Barthrup', 3, false, '2025-01-18', false, 'INVITED', 'In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum.', 'Pellentesque ultrices mattis odio. Donec vitae nisi.', '2024-07-06 16:39:48+02', 45, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (13, 'meppsc@seesaa.net', 'MRS', 'Régine', 'Epps', 10, true, '2024-12-19', NULL, 'INVITED', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', '2024-08-26 18:05:41+02', 50, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (14, 'ttrewhellad@qq.com', 'MRS', 'Wá', 'Trewhella', 1, true, '2024-06-06', true, 'DECLINED', 'Proin at turpis a pede posuere nonummy. Integer non velit.', 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit.', '2025-01-27 12:48:24+01', 17, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (15, 'bseverne@gizmodo.com', 'MRS', 'Céline', 'Severn', 8, true, '2024-06-06', NULL, 'CREATED', 'Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', '2025-02-10 02:53:07+01', 47, 'MANUAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (16, 'opereiraf@geocities.jp', 'MRS', NULL, 'Pereira', 4, false, '2024-12-22', NULL, 'INVITED', 'Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis.', '2024-11-10 19:26:43+01', 17, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (17, 'elancastleg@istockphoto.com', 'MR', 'Léonore', 'Lancastle', 2, true, '2024-09-19', true, 'CREATED', 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.', 'Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', '2025-02-27 01:31:16+01', 12, 'MANUAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (18, 'msquibbsh@bluehost.com', 'MR', 'Cunégonde', 'Squibbs', 5, true, '2024-08-10', NULL, 'DECLINED', 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis.', 'Donec semper sapien a libero.', '2024-05-19 02:35:03+02', 23, 'MANUAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (19, 'mbierlingi@soup.io', 'MR', 'Sélène', 'Bierling', 5, true, '2024-06-21', true, 'INVITED', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', '2025-02-23 13:07:04+01', 41, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (20, 'tindgsj@acquirethisname.com', 'MRS', 'Maëlys', 'Indgs', 9, true, '2024-07-18', true, 'DECLINED', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2024-10-18 20:37:06+02', 24, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (21, 'dnipperk@google.de', 'MR', 'Maïly', 'Nipper', 10, true, '2024-08-04', NULL, 'INVITED', 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.', 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis.', '2024-07-08 02:56:56+02', 21, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (22, 'kadeyl@unesco.org', 'MR', 'Björn', 'Adey', 1, false, '2024-05-11', false, 'CREATED', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.', 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.', '2025-01-17 03:12:03+01', 46, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (23, 'nscadm@princeton.edu', 'MRS', 'Fèi', 'Scad', 2, false, '2024-11-11', false, 'CREATED', 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl.', 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus.', '2024-11-02 03:00:33+01', 19, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (24, 'cgirodonn@weibo.com', 'MRS', 'Marie-josée', 'Girodon', 6, true, '2024-10-26', NULL, 'DECLINED', 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', '2024-10-22 11:07:18+02', 33, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (25, 'mmckimmieo@columbia.edu', 'MR', NULL, 'McKimmie', 2, false, '2024-12-18', NULL, 'INVITED', 'Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.', '2025-03-08 15:08:25+01', 46, 'MANUAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (26, 'aaslenp@nytimes.com', 'MR', 'Aloïs', 'Aslen', 10, false, '2025-02-07', true, 'CREATED', 'Integer a nibh. In quis justo.', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '2025-01-09 03:15:35+01', 44, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (27, 'hcattonq@ucla.edu', 'MR', NULL, 'Catton', 8, true, '2024-08-10', NULL, 'DECLINED', 'Aliquam non mauris. Morbi non lectus.', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo.', '2025-02-04 18:30:57+01', 14, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (28, 'gtamblynr@comcast.net', 'MR', 'Adélaïde', 'Tamblyn', 2, true, '2024-06-22', NULL, 'CREATED', 'Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.', '2025-01-22 12:55:11+01', 12, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (29, 'ctebbets@free.fr', 'MRS', 'Annotée', 'Tebbet', 9, false, '2025-01-02', false, 'INVITED', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 'Morbi a ipsum.', '2024-04-21 07:43:55+02', 5, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (30, 'rdecourcyt@ow.ly', 'MR', NULL, 'de Courcy', 7, true, '2024-11-27', NULL, 'DECLINED', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo.', 'Nulla ut erat id mauris vulputate elementum.', '2025-01-27 09:49:12+01', 22, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (31, 'vhubachu@huffingtonpost.com', 'MRS', 'Daphnée', 'Hubach', 4, true, '2024-06-12', NULL, 'CREATED', 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl.', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.', '2024-11-07 18:12:52+01', 10, 'MANUAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (32, 'dsandbrookv@sbwire.com', 'MR', 'Tú', 'Sandbrook', 7, true, '2024-09-05', false, 'CREATED', 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.', 'Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.', '2024-09-25 05:47:27+02', 3, 'MANUAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (33, 'adastw@msu.edu', 'MRS', 'Maëlle', 'Dast', 4, true, '2024-09-28', NULL, 'INVITED', 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', '2024-06-30 13:32:30+02', 6, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (34, 'dgrishankovx@acquirethisname.com', 'MRS', 'Angélique', 'Grishankov', 4, true, '2025-03-12', NULL, 'DECLINED', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.', 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.', '2024-12-19 18:24:51+01', 20, 'MANUAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (35, 'cflinty@skyrock.com', 'MR', 'Yáo', 'Flint', 10, true, '2025-01-29', false, 'CREATED', 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.', '2024-12-07 08:38:21+01', 10, 'MANUAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (36, 'mchamberlainz@de.vu', 'MR', 'Andréa', 'Chamberlain', 4, false, '2024-09-16', NULL, 'DECLINED', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '2024-11-09 12:59:23+01', 40, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (37, 'ebeauvais10@eventbrite.com', 'MR', 'Maëline', 'Beauvais', 3, false, '2024-08-27', false, 'INVITED', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.', 'Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', '2025-02-01 04:19:46+01', 3, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (38, 'igabitis11@chicagotribune.com', 'MR', 'Amélie', 'Gabitis', 10, false, '2024-10-17', NULL, 'CREATED', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis.', 'Nulla ut erat id mauris vulputate elementum.', '2025-03-14 12:52:51+01', 39, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (39, 'mfanning12@yandex.ru', 'MRS', 'Maëlys', 'Fanning', 7, true, '2024-04-11', true, 'DECLINED', 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.', '2024-06-08 04:24:57+02', 13, 'MANUAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (40, 'dhenriques13@weather.com', 'MR', 'Mylène', 'Henriques', 3, false, '2024-03-19', false, 'INVITED', 'Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', '2024-06-20 13:21:45+02', 7, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (41, 'eashlee14@unblog.fr', 'MR', 'Salomé', 'Ashlee', 8, false, '2024-09-17', NULL, 'CREATED', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante.', 'Proin eu mi. Nulla ac enim.', '2024-06-25 11:21:51+02', 21, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (42, 'kdigman15@sohu.com', 'MRS', 'Réservés', 'Digman', 1, true, '2024-09-15', NULL, 'CREATED', 'Aenean fermentum.', 'Aliquam quis turpis eget elit sodales scelerisque.', '2024-06-14 03:37:32+02', 5, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (43, 'dgerren16@ucsd.edu', 'MR', 'Mà', 'Gerren', 2, true, '2024-04-10', true, 'INVITED', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus.', 'Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', '2024-07-01 18:13:34+02', 15, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (44, 'nprobate17@techcrunch.com', 'MR', NULL, 'Probate', 6, false, '2025-02-19', NULL, 'INVITED', 'Proin risus.', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', '2024-04-15 12:36:57+02', 22, 'MANUAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (45, 'selrick18@uiuc.edu', 'MR', 'Méthode', 'Elrick', 8, true, '2025-02-02', true, 'INVITED', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.', '2025-01-28 10:12:29+01', 11, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (46, 'jnormansell19@businessinsider.com', 'MRS', NULL, 'Normansell', 6, false, '2024-10-16', true, 'DECLINED', 'Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', '2024-06-27 22:44:46+02', 11, 'MANUAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (47, 'lguisby1a@people.com.cn', 'MR', 'Marie-françoise', 'Guisby', 4, false, '2024-10-20', false, 'CREATED', 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.', '2024-11-05 16:43:09+01', 35, 'MANUAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (48, 'maguirrezabala1b@tamu.edu', 'MRS', 'Anaé', 'Aguirrezabala', 8, true, '2025-01-03', false, 'DECLINED', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero.', 'In quis justo.', '2025-02-13 21:36:53+01', 43, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (49, 'asavary1c@bizjournals.com', 'MRS', 'Maëlys', 'Savary', 9, true, '2025-01-03', true, 'INVITED', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo.', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', '2024-04-17 20:56:42+02', 26, 'MANUAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (50, 'jgilbee1d@storify.com', 'MR', 'Lauréna', 'Gilbee', 2, true, '2024-06-10', NULL, 'INVITED', 'Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.', 'Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.', '2024-04-28 07:21:42+02', 7, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (51, 'achittey1e@upenn.edu', 'MR', 'Nélie', 'Chittey', 5, false, '2025-03-08', NULL, 'DECLINED', 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante.', 'Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', '2025-01-30 09:53:23+01', 47, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (52, 'rbeddall1f@comcast.net', 'MRS', NULL, 'Beddall', 7, false, '2024-08-15', true, 'CREATED', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.', 'Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio.', '2024-07-30 05:01:18+02', 13, 'MANUAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (53, 'mtedahl1g@netlog.com', 'MR', 'Ruì', 'Tedahl', 6, false, '2024-08-22', true, 'CREATED', 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', '2024-10-27 00:42:01+02', 35, 'MANUAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (54, 'tfinlay1h@mozilla.org', 'MR', 'Méng', 'Finlay', 9, true, '2024-11-12', false, 'DECLINED', 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.', 'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', '2024-11-19 11:33:52+01', 20, 'MANUAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (55, 'sgopsell1i@wikispaces.com', 'MRS', 'Renée', 'Gopsell', 1, true, '2024-06-12', false, 'INVITED', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'Phasellus in felis. Donec semper sapien a libero.', '2024-07-13 21:54:37+02', 9, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (56, 'ieckford1j@mlb.com', 'MRS', 'Mélissandre', 'Eckford', 2, true, '2024-09-09', true, 'DECLINED', 'Nulla ut erat id mauris vulputate elementum.', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.', '2024-04-04 01:57:21+02', 41, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (57, 'amertsching1k@hhs.gov', 'MRS', 'Chloé', 'Mertsching', 6, false, '2024-04-19', true, 'INVITED', 'Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo.', 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.', '2024-07-26 06:23:28+02', 38, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (58, 'rbrownhall1l@goo.gl', 'MRS', 'Ruì', 'Brownhall', 5, true, '2024-09-05', NULL, 'DECLINED', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.', '2024-12-16 08:35:52+01', 37, 'MANUAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (59, 'hvarfalameev1m@quantcast.com', 'MR', 'Marie-noël', 'Varfalameev', 9, false, '2024-07-04', false, 'DECLINED', 'Quisque ut erat. Curabitur gravida nisi at nibh.', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.', '2024-10-26 06:28:42+02', 15, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (60, 'ldinsell1n@irs.gov', 'MR', 'Pål', 'Dinsell', 3, true, '2024-04-22', true, 'CREATED', 'Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 'Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.', '2024-05-06 23:14:35+02', 19, 'MANUAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (61, 'tdubber1o@ocn.ne.jp', 'MR', 'Åslög', 'Dubber', 10, true, '2025-03-06', NULL, 'INVITED', 'Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', '2024-04-20 19:11:52+02', 7, 'MANUAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (62, 'creinbach1p@360.cn', 'MRS', 'Cécilia', 'Reinbach', 10, true, '2025-02-05', NULL, 'DECLINED', 'Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.', 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.', '2024-08-26 21:15:01+02', 19, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (63, 'etrappe1q@amazon.de', 'MRS', 'Marie-thérèse', 'Trappe', 2, false, '2024-10-23', NULL, 'INVITED', 'Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.', '2024-09-16 04:26:19+02', 21, 'MANUAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (64, 'ominster1r@ameblo.jp', 'MR', 'Zhì', 'Minster', 10, true, '2024-05-04', false, 'DECLINED', 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla.', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', '2024-08-16 17:20:28+02', 25, 'MANUAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (65, 'tditchett1s@bing.com', 'MRS', NULL, 'Ditchett', 9, true, '2024-07-27', NULL, 'INVITED', 'Aliquam erat volutpat. In congue. Etiam justo.', 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat.', '2024-11-12 11:17:16+01', 4, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (66, 'msuller1t@usda.gov', 'MRS', 'Chloé', 'Suller', 4, true, '2024-10-17', true, 'INVITED', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', '2024-03-31 04:21:19+02', 38, 'MANUAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (67, 'rfirpo1u@forbes.com', 'MR', 'Léonie', 'Firpo', 7, true, '2024-11-15', NULL, 'DECLINED', 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim.', 'Nulla suscipit ligula in lacus.', '2024-04-26 16:34:05+02', 30, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (68, 'gsoots1v@newyorker.com', 'MR', 'Adélie', 'Soots', 9, false, '2025-03-11', NULL, 'INVITED', 'Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.', '2024-12-09 08:19:27+01', 34, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (69, 'veassom1w@tripod.com', 'MR', NULL, 'Eassom', 6, false, '2024-07-12', NULL, 'DECLINED', 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.', 'Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.', '2024-08-29 06:31:57+02', 11, 'MANUAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (70, 'mbyng1x@cnet.com', 'MRS', 'Annotée', 'Byng', 3, true, '2025-02-28', NULL, 'DECLINED', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo.', 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', '2025-03-12 08:33:17+01', 5, 'MANUAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (71, 'lcameli1y@prlog.org', 'MRS', 'Céline', 'Cameli', 2, true, '2024-09-24', NULL, 'DECLINED', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.', '2024-11-01 12:11:40+01', 10, 'MANUAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (72, 'cpeteri1z@fastcompany.com', 'MR', NULL, 'Peteri', 6, false, '2024-10-20', NULL, 'CREATED', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.', '2024-06-07 07:01:13+02', 23, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (73, 'ajosifovic20@dyndns.org', 'MR', NULL, 'Josifovic', 3, true, '2024-10-26', false, 'CREATED', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', '2024-12-14 10:33:27+01', 4, 'MANUAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (74, 'bkerwen21@icq.com', 'MRS', 'Vénus', 'Kerwen', 8, true, '2024-07-18', NULL, 'INVITED', 'Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui.', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl.', '2024-07-10 23:49:42+02', 40, 'MANUAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (75, 'ckirkness22@deliciousdays.com', 'MR', 'Chloé', 'Kirkness', 1, true, '2024-08-08', false, 'CREATED', 'Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio.', 'Nulla tempus.', '2024-10-05 12:06:29+02', 42, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (76, 'bpressland23@wiley.com', 'MR', 'Célestine', 'Pressland', 4, true, '2025-02-05', NULL, 'INVITED', 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit.', '2025-01-28 22:10:03+01', 14, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (77, 'bcousin24@drupal.org', 'MR', 'Táng', 'Cousin', 10, true, '2024-04-22', true, 'DECLINED', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc.', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '2024-05-13 10:36:49+02', 45, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (78, 'mdabel25@theatlantic.com', 'MR', 'Anaé', 'Dabel', 2, true, '2024-04-20', false, 'DECLINED', 'Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus.', 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', '2024-11-22 23:36:53+01', 33, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (79, 'amuir26@histats.com', 'MRS', NULL, 'Muir', 1, true, '2025-03-04', false, 'INVITED', 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 'Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', '2024-03-17 19:10:14+01', 26, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (80, 'iruzicka27@spotify.com', 'MR', 'Renée', 'Ruzicka', 7, false, '2024-09-21', true, 'CREATED', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.', '2024-05-19 07:39:27+02', 25, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (81, 'bemmanueli28@ibm.com', 'MRS', 'Mélanie', 'Emmanueli', 3, true, '2024-05-19', true, 'DECLINED', 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', '2024-06-12 16:18:35+02', 20, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (82, 'vmattecot29@diigo.com', 'MRS', 'Andréa', 'Mattecot', 1, true, '2024-06-14', true, 'CREATED', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.', 'Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.', '2025-01-07 11:59:51+01', 1, 'MANUAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (83, 'smunson2a@artisteer.com', 'MRS', 'Noémie', 'Munson', 1, false, '2024-12-06', false, 'DECLINED', 'Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', '2024-07-24 19:51:03+02', 34, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (84, 'acoudray2b@mtv.com', 'MR', 'Loïs', 'Coudray', 1, true, '2025-03-10', true, 'DECLINED', 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl.', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.', '2025-01-29 02:18:04+01', 49, 'MANUAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (85, 'pmcfetrich2c@si.edu', 'MR', 'Daphnée', 'McFetrich', 7, true, '2024-06-12', true, 'CREATED', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.', '2024-11-29 00:26:18+01', 27, 'MANUAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (86, 'jisakovitch2d@yellowbook.com', 'MR', 'Erwéi', 'Isakovitch', 2, false, '2024-07-31', NULL, 'DECLINED', 'Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.', 'Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', '2024-05-30 03:24:02+02', 29, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (87, 'sslisby2e@ibm.com', 'MR', 'Loïs', 'Slisby', 7, false, '2025-03-08', true, 'INVITED', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.', 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', '2024-11-16 16:40:18+01', 31, 'MANUAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (88, 'jrailton2f@bizjournals.com', 'MRS', 'Miléna', 'Railton', 1, false, '2024-10-07', NULL, 'INVITED', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.', 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', '2024-10-07 04:41:06+02', 23, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (89, 'boslar2g@unicef.org', 'MR', 'Léa', 'Oslar', 5, true, '2025-02-14', NULL, 'CREATED', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'Donec quis orci eget orci vehicula condimentum.', '2024-04-30 17:37:42+02', 1, 'MANUAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (90, 'mpavitt2h@nsw.gov.au', 'MRS', 'Uò', 'Pavitt', 7, true, '2025-01-09', NULL, 'INVITED', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.', '2025-01-11 11:48:41+01', 37, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (91, 'lwaight2i@nba.com', 'MRS', 'Kallisté', 'Waight', 5, true, '2024-11-02', true, 'INVITED', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae, Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', '2024-05-14 07:38:51+02', 50, 'MANUAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (92, 'uragbourne2j@mashable.com', 'MR', 'Léana', 'Ragbourne', 2, false, '2025-03-01', true, 'INVITED', 'Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti.', '2024-11-20 04:48:46+01', 46, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (93, 'brioch2k@dion.ne.jp', 'MRS', 'Lucrèce', 'Rioch', 10, true, '2024-04-09', NULL, 'INVITED', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 'Integer ac neque.', '2024-07-03 07:03:27+02', 23, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (94, 'crosthorn2l@cargocollective.com', 'MRS', 'Kuí', 'Rosthorn', 7, false, '2024-06-24', NULL, 'CREATED', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '2024-12-29 15:24:17+01', 6, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (95, 'zferrieres2m@google.com.hk', 'MRS', 'Björn', 'Ferrieres', 6, true, '2024-11-21', NULL, 'INVITED', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '2024-05-01 12:04:40+02', 36, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (96, 'hmeehan2n@china.com.cn', 'MR', 'Célestine', 'Meehan', 8, true, '2024-10-24', true, 'INVITED', 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.', '2025-03-13 10:02:59+01', 25, 'MANUAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (97, 'dcrossfeld2o@mail.ru', 'MRS', NULL, 'Crossfeld', 5, true, '2024-11-09', true, 'CREATED', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', 'Nulla tellus. In sagittis dui vel nisl. Duis ac nibh.', '2025-01-03 01:18:39+01', 46, 'MANUAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (98, 'sblazeby2p@nasa.gov', 'MR', NULL, 'Blazeby', 5, false, '2024-04-26', true, 'CREATED', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim.', '2024-09-21 22:14:17+02', 23, 'MANUAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (99, 'rlydford2q@printfriendly.com', 'MRS', 'Géraldine', 'Lydford', 8, false, '2025-01-07', NULL, 'DECLINED', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 'Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.', '2024-09-26 03:13:32+02', 50, 'PORTAL');
INSERT INTO wohnungshelden.applicants (id, email, salutation, first_name, last_name, number_of_persons, wbs_present, earliest_move_in_date, pets, status, applicant_comment, user_comment, creation_timestamp, property_id, creation_source) VALUES (100, 'amauchlen2r@csmonitor.com', 'MRS', 'Intéressant', 'Mauchlen', 10, true, '2024-12-16', true, 'INVITED', 'Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', 'Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', '2024-04-14 02:26:55+02', 14, 'MANUAL');


--
-- TOC entry 4798 (class 0 OID 0)
-- Dependencies: 217
-- Name: applicants_seq; Type: SEQUENCE SET; Schema: wohnungshelden; Owner: test
--

SELECT pg_catalog.setval('wohnungshelden.applicants_seq', 101, false);


--
-- TOC entry 4646 (class 2606 OID 16563)
-- Name: applicants applications_pk; Type: CONSTRAINT; Schema: wohnungshelden; Owner: test
--

ALTER TABLE ONLY wohnungshelden.applicants
    ADD CONSTRAINT applications_pk PRIMARY KEY (id);


-- Completed on 2025-03-16 20:31:59

--
-- PostgreSQL database dump complete
--

